#SPDX-License-Identifier: MIT OR CC0-1.0
# Bryn (ARA)

trailingComma: all
singleQuote: true

overrides:
  - files: "*.md"
    options:
      printWidth: 120
      proseWrap: always
      semi: true
      singleQuote: true
      quoteProps: as-needed
      trailingComma: all
