/* SPDX-License-Identifier: MIT
Animal Rights Advocates */

enum TOPICS {
  APOLLO_CLIENT = 'APOLLO_CLIENT',
  APOLLO_SERVER = 'APOLLO_SERVER',
  DISCORD = 'DISCORD',
  DISCORD_SHARD = 'DISCORD_SHARD',
  METRICS = 'METRICS',
  NEXUS = 'NEXUS',
  NODE = 'NODE',
  POLL = 'POLL',
  RPC = 'RPC',
  SAPPHIRE = 'SAPPHIRE',
  UNHANDLED_REJECTION = 'UNHANDLED_REJECTION',
}

export default TOPICS;
